# Generated by Django 5.2 on 2025-04-24 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
