# Generated by Django 5.2 on 2025-04-24 23:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0002_procedure_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='concerned_users',
            field=models.ManyToManyField(blank=True, related_name='concerned_procedures', to=settings.AUTH_USER_MODEL),
        ),
    ]
