# Generated by Django 5.2 on 2025-04-26 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0006_remove_activitydetail_duration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedureNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new', 'Nouvelle procédure'), ('update', 'Mise à jour procédure')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('message', models.TextField()),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procedures.procedure')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedure_notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProcedureReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('read_date', models.DateTimeField(blank=True, null=True)),
                ('is_signed', models.BooleanField(default=False)),
                ('signed_date', models.DateTimeField(blank=True, null=True)),
                ('signature_data', models.TextField(blank=True, null=True)),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_status', to='procedures.procedure')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedure_reads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'procedure')},
            },
        ),
    ]
