# Generated by Django 5.2 on 2025-04-29 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0008_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procedurenotification',
            options={'ordering': ['-created_at']},
        ),
    ]
